// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vod2Tube.Infrastructure;

#nullable disable

namespace Vod2Tube.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260313025815_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Vod2Tube.Domain.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAtUTC")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("Vod2Tube.Domain.Pipeline", b =>
                {
                    b.Property<string>("VodId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatTextFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatVideoFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FailCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Failed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FinalVideoFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumableUploadUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VodFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YoutubeVideoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VodId");

                    b.ToTable("Pipelines");
                });

            modelBuilder.Entity("Vod2Tube.Domain.TwitchVod", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAtUTC")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TwitchVods");
                });
#pragma warning restore 612, 618
        }
    }
}
